repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [ --fix ]

  - repo: local
    hooks:
      - id: tombi
        name: tombi fmt
        entry: uv run tombi fmt
        language: system
        types: [toml]